#!/usr/bin/env python3
"""Build the paste-ready boxes of the CF care skills from one shared core, so the core cannot drift between skills.

Usage:  python scripts/make_paste_ready.py [ROOT] [--check]

ROOT defaults to the folder above scripts/. Every skill in .claude/skills/ that has a references/paste-parts.md gets:

- in references/paste-ready.md, the part from the first '## SHORT' heading up to the '## Try it' heading rewritten
  with two boxes, SHORT and STANDARD, each inside a ```text fence between the START and END marker lines that
  tests/test_paste_ready.py reads. Everything else in that file (How to use this, Try it, what the version cannot do,
  the evidence link) is kept as it is on disk;
- in SKILL.md, the text between the lines <!-- paste-standard:start --> and <!-- paste-standard:end --> replaced by
  the STANDARD box, inside a ```text fence, so the skill's rules and its standard box are one text.

A box is: the skill's role line, the shared core (shared/paste-core/core-short.txt or core-standard.txt, copied
verbatim, so each box works alone when pasted), the skill's task part, then its end lines. The STANDARD box also has
the shared silent-check line (shared/paste-core/check-line.txt) before its end lines. A skill's parts are the
```text fences under the headings SHORT role, SHORT task, SHORT end, STANDARD role, STANDARD task and STANDARD end
in its references/paste-parts.md; an empty fence means no part.

Without --check it writes the files that changed. With --check it writes nothing and exits 1 if any file is out of
date. Exit 1 also when a box is over its limit (SHORT 1,200 characters, STANDARD 3,300) or a file lacks its markers;
exit 2 on a usage error. Standard library only; no network; no subprocess.
"""

import re
import sys
from pathlib import Path

SKILLS_REL = Path(".claude") / "skills"
CORE_REL = Path("shared") / "paste-core"
PARTS = ("SHORT role", "SHORT task", "SHORT end", "STANDARD role", "STANDARD task", "STANDARD end")
LIMITS = {"SHORT": 1200, "STANDARD": 3300}
START = "=== START: copy from here ==="
END = "=== END: copy to here ==="
SKILL_START = "<!-- paste-standard:start -->"
SKILL_END = "<!-- paste-standard:end -->"
NOTE = ("<!-- Generated by scripts/make_paste_ready.py from shared/paste-core/ and references/paste-parts.md. "
        "Edit those, then run the script. -->")


class Problem(Exception):
    pass


def read(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def read_core(root: Path) -> dict:
    core = {}
    for key, name in (("SHORT", "core-short.txt"), ("STANDARD", "core-standard.txt"), ("CHECK", "check-line.txt")):
        p = root / CORE_REL / name
        if not p.is_file():
            raise Problem(f"ERROR {CORE_REL.as_posix()}/{name}: missing")
        text = read(p).strip("\n")
        if not text.strip():
            raise Problem(f"ERROR {CORE_REL.as_posix()}/{name}: empty")
        core[key] = text
    return core


def parse_parts(text: str, where: str) -> dict:
    """Return {part name: text} from a paste-parts.md: the ```text fence under each '## <part name>' heading."""
    parts = {}
    for name in PARTS:
        m = re.search(r"^## " + re.escape(name) + r"[ \t]*\n+```text[ \t]*\n(.*?)^```[ \t]*$", text, re.M | re.S)
        if not m:
            raise Problem(f"ERROR {where}: no '## {name}' heading followed by a ```text fence")
        parts[name] = m.group(1).strip("\n")
    for name in ("SHORT role", "SHORT end", "STANDARD role", "STANDARD end"):
        if not parts[name].strip():
            raise Problem(f"ERROR {where}: '{name}' is empty")
    return parts


def build_boxes(core: dict, parts: dict) -> dict:
    short = "\n".join(x for x in (parts["SHORT role"], core["SHORT"], parts["SHORT task"], parts["SHORT end"]) if x)
    standard = "\n\n".join(x for x in (parts["STANDARD role"] + "\n" + core["STANDARD"], parts["STANDARD task"],
                                       core["CHECK"] + "\n" + parts["STANDARD end"]) if x)
    return {"SHORT": short, "STANDARD": standard}


def boxes_markdown(boxes: dict) -> str:
    out = [NOTE, ""]
    for name in ("SHORT", "STANDARD"):
        out += [f"## {name} box ({len(boxes[name]):,} characters)", "", START, "```text", boxes[name], "```", END, ""]
    return "\n".join(out)


def render_paste_ready(old: str, boxes: dict, where: str) -> str:
    m = re.search(r"^## SHORT\b", old, re.M)
    t = re.search(r"^## Try it\b", old, re.M)
    if not m or not t or t.start() < m.start():
        raise Problem(f"ERROR {where}: needs a '## SHORT' heading and, below it, a '## Try it' heading")
    # keep a generated note that sits right above the first SHORT heading out of the kept text
    head = old[:m.start()]
    if head.rstrip("\n").endswith(NOTE):
        head = head.rstrip("\n")[:-len(NOTE)]
    return head.rstrip("\n") + "\n\n" + boxes_markdown(boxes) + "\n" + old[t.start():]


def render_skill(old: str, standard: str, where: str) -> str:
    s = old.find(SKILL_START)
    e = old.find(SKILL_END)
    if s == -1 or e == -1 or e < s or old.count(SKILL_START) != 1 or old.count(SKILL_END) != 1:
        raise Problem(f"ERROR {where}: needs one line {SKILL_START} and, below it, one line {SKILL_END}")
    inner = "\n```text\n" + standard + "\n```\n"
    return old[:s + len(SKILL_START)] + inner + old[e:]


def plan(root: Path):
    """Return (list of (path, new text), list of (skill, sizes)). Raises Problem."""
    core = read_core(root)
    skills_dir = root / SKILLS_REL
    if not skills_dir.is_dir():
        raise Problem(f"ERROR {SKILLS_REL.as_posix()}: missing")
    writes, sizes, problems = [], [], []
    for folder in sorted(p for p in skills_dir.iterdir() if (p / "references" / "paste-parts.md").is_file()):
        rel = (SKILLS_REL / folder.name).as_posix()
        parts = parse_parts(read(folder / "references" / "paste-parts.md"), rel + "/references/paste-parts.md")
        boxes = build_boxes(core, parts)
        for name, limit in LIMITS.items():
            if len(boxes[name]) > limit:
                problems.append(f"ERROR {rel}: the {name} box has {len(boxes[name]):,} characters; the limit is {limit:,}")
        sizes.append((folder.name, {k: len(v) for k, v in boxes.items()}))
        pr = folder / "references" / "paste-ready.md"
        if not pr.is_file():
            problems.append(f"ERROR {rel}/references/paste-ready.md: missing")
        else:
            writes.append((pr, render_paste_ready(read(pr), boxes, rel + "/references/paste-ready.md")))
        sm = folder / "SKILL.md"
        writes.append((sm, render_skill(read(sm), boxes["STANDARD"], rel + "/SKILL.md")))
    if not sizes:
        problems.append(f"ERROR {SKILLS_REL.as_posix()}: no skill has references/paste-parts.md")
    if problems:
        raise Problem("\n".join(problems))
    return writes, sizes


def main(argv=None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    check = "--check" in args
    rest = [a for a in args if a != "--check"]
    if len(rest) > 1 or any(a.startswith("-") for a in rest):
        print("usage: python scripts/make_paste_ready.py [ROOT] [--check]", file=sys.stderr)
        return 2
    root = Path(rest[0]).resolve() if rest else Path(__file__).resolve().parent.parent
    if not root.is_dir():
        print(f"ERROR: ROOT '{root}' is not an existing folder", file=sys.stderr)
        return 2
    try:
        writes, sizes = plan(root)
    except Problem as exc:
        print(exc)
        return 1
    stale = [(p, text) for p, text in writes if read(p) != text]
    for name, s in sizes:
        print(f"{name}: SHORT {s['SHORT']:,} characters, STANDARD {s['STANDARD']:,}")
    if check:
        for p, _ in stale:
            print(f"ERROR {p.relative_to(root).as_posix()}: out of date; run python scripts/make_paste_ready.py")
        if stale:
            return 1
        print("ok")
        return 0
    for p, text in stale:
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote {p.relative_to(root).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
